### PR TITLE
Position moves when zooming

### LINKED ISSUE #257: Position moves when zooming
When viewing an existing report, you can zoom in and out of the map *but* that moves the center of the "pin" and so you can't see where the report was generated. The pin should stay in the same place.

### PR DESCRIPTION
**Pull request by akaktus**
[-] Added center in the mapViewDidChangeVisibleRegion(_ mapView: MKMapView)
Fixes #257

### CODE REVIEW

**Review by am-MongoDB — CHANGES_REQUESTED** [review]
Now pinch and pull only adjust the zoom by a tiny amount - makes it pretty unusable. You can double tap to zoom in a little bit faster (but very few people would know to triple-tap to zoom back out again

**Comment by o-fish-wildaid** [comment]
[Review PRs](https://trello.com/c/LIywX167/325-review-prs)

**Comment by am-MongoDB** [comment]
On on an iPhone, Zooming in works but then it springs back to the original zoom level when I release my fingers. After trying several times, I get this error appear many times: `2020-09-21 16:16:27.300755+0100 O-FISH[7431:3131057] [VKDefault] Style Z is requested for an invisible rect`. After a while,  before it starts working correctly.

**Comment by am-MongoDB** [comment]
Just tested again and I'm seeing the same behaviour

**Comment by akaktus** [comment]
> On on an iPhone, Zooming in works but then it springs back to the original zoom level when I release my fingers. After trying several times, I get this error appear many times: `2020-09-21 16:16:27.300755+0100 O-FISH[7431:3131057] [VKDefault] Style Z is requested for an invisible rect`. After a while, before it starts working correctly.

This error is doesn't affect functionality. BTW I can't find solution for that.

**Review by am-MongoDB — APPROVED** [review]

**Pull request merged**
