### PR TITLE
Make permit number appear in all caps on vessel information page

### LINKED ISSUE #245: Permit # all caps
Is there any way we can have the Permit number (under vessel information) appear in all caps? The keyboard should come up as all caps so the user enters any letters as capital.

### PR DESCRIPTION
**Pull request by nugmanoff**
Closes #245 

This one is also is a part of Hacktoberfest 2020 :)

### CODE REVIEW

**Comment by Sheeri** [comment]
Hi @nugmanoff - I see you've submitted another PR - we love to see it! Our team will review this before this time on Monday (3 business days). 

Thanks so much for your contributions!

**Review by Sheeri — CHANGES_REQUESTED** [review]
(extraneous commits)

**Comment by nugmanoff** [comment]
@Sheeri I tried to get rid of them but no luck so far. I can't really understand why it even occurred, can you give me some directions on how to fix it?

**Comment by Sheeri** [comment]
What I've done in the past is:

go into a new directory and clone there, let's say I'm in ~sheeri/github/o-fish-ios
I will cd ../ to get to ~sheeri/github
Then clone into a new directory:

git clone https://github.com/WildAid/o-fish-ios.git o-fish-ios-clean

Then look at the files I know I changed, and resubmit only those changes (by copying the files, or by making the changes again).

**Comment by Sheeri** [comment]
Looks like you figured it out while I was typing an answer! 👍

**Comment by Sheeri** [comment]
@nugmanoff Just one more - the README file...you're so close!

**Comment by nugmanoff** [comment]
@Sheeri this one got messed up & accidentally closed ;( I opened a new one #343, so sorry for bloating the repo

**Pull request closed without merging**
