### PR TITLE
Initial darkmode implementation

### LINKED ISSUE #347: Add Dark Mode button and change the 'Me' page accordingly
Users frequently find themselves in situations where they are using the app in very bright sunlight, or at night. Please add a Dark Mode button, and change the 'Me' page accordingly. 

This is the screen when the user clicks their avatar on the home screen. 

The screen should look like this - https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591779_Me
Dark mode is off by default, and has the light background; when Dark mode is toggled on, the dark theme should be applied. 

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode  
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode   
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not).

This profile setting should be stored on the device, not in the database. 

Dark mode should work either when the switch is toggled on, or when the switch is off but the device itself is in dark mode.

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

### PR DESCRIPTION
**Pull request by bladebunny**
## Related Issue

Fixes #347 
Changing the mode on the profile page now changes the color scheme.  I have not changed all colors.  Some views will auto-change based on the system colors.  But we will need to go through and ensure views are using a correct color set color that is based on the design instead if relying on defaults. 

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [x] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 
This PR includes a slight re-org of the Assets catalog.  I needed to add some color sets so I added sub-folders for icons and colors.  I also added a loc file before seeing the pre-existing one.  I have a slightly different way of doing string loc that does not require raw strings in views.  Please take a look and let me know if you want to use my method or have me revert and use the previous approach.

* **Optional: Add any relevant screenshots here**

### CODE REVIEW

**Review by Sheeri — CHANGES_REQUESTED** [review]
Hi @bladebunny 

Dark mode is *almost* perfect! The one part that's not in dark mode is the white bar at the top that has the "Close" text to close the profile. 

Can you submit a patch for that please?
IMG_9196

**Comment by bladebunny** [comment]
Shoot. I thought I was handling that as it wasn't doing this in my testing - but I did see this in my first attempt. What device / OS was this on? SwiftUI seems not to be handling the color scheme change. This one is tough because we don't have access to the navbar background from that view. 

Have also tried appearance proxy but that can result in weird inconsistencies where navbar appearance doesn't match the rest of the color scheme.  Also, because the app hides the bar on the patrol view but then shows it when presenting profile view (and then hides again when navigating back) it gets glitchy when you are trying to toggle the navbar appearance in between. 

Anyway, I'll take another look but it may take two or three days. (I've tried two or three 'standard' approaches already.)

Do let me know about device / OS in case it's a known SwiftUI issue.

**Review by Sheeri — APPROVED** [review]

**Comment by Sheeri** [comment]
Interesting! I tried on 2 different emulators, iPhone 8 and iPhone 11, and they both worked. 

The physical device I had was an iPhone 7. I checked if there was a software update and there was (usually it shows an alert when there's an update, but there was no alert). It's in the process of updating now.

The code functionality is there and working, so there's nothing to change from that aspect. I'm going to kick it over to @am-MongoDB for an actual review of the code itself (I'm not an iOS developer). It may take a bit to review; if you want to work on another issue in the meantime, just comment on it and we'll assign it to you.

**Comment by bladebunny** [comment]
I adding some additional logic to force the system to use the chosen mode on launch and then again on a settings change.  It should already have been working but this will harden it somewhat.  Trying to lean into the dark mode settings system so as to reduce the need for lots of hard checks on selected mode and setting colors.

I also made some tweaks to / suggest change to Localization if you could take a look.  Not trying to do all that work here but I needed loc for the new toggle button.  I know SwiftUI can handle a direct loc lookup but it still results in lots of raw strings all over the place.  I like to use path-encode loc string ids so as not to confuse with the actual content of the string - so if there's loc failure you will see the coded string and know there's no matching loc.  You can then wrap these in structs with static vars so you never need raw strings in views.

**Comment by bladebunny** [comment]
I just pushed an update with the additional logic.  It seems to work on my two test devices (iPhone 11 and 8) as well as on simulator.  
**Note:** You will need to re-add signing authority in Xcode. Sorry.  I needed to change it to test on device because I don't have your team cert.  You just need to go to 'Signing and Capabilities' on the target and re-add the Team.

**Comment by bladebunny** [comment]
Closing this PR and will re-submit. I can't see these conflicts from Git for some reason so will re-synch and republish.

**Pull request closed without merging**
