### PR TITLE
Change EMS registry number input field keyboard type to numeric

### LINKED ISSUE #246: EMS registry number should be a number
Please show the numeric keyboard as default for entering information into the EMS section - registry number.

### PR DESCRIPTION
**Pull request by nugmanoff**
Hey there! I am happy to contribute to your repository as part of Hacktoberfest 2020

This PR Closes #246

### CODE REVIEW

**Comment by Sheeri** [comment]
Hi @nugmanoff - Thanks so much for this pull request! It's the details like this that make an app really spectacular - having a numeric keypad when the user is typing numbers.

If you could comment on #246 that would be great, so we can assign the issue to you (so nobody else tries to do it, if they see it's unassigned).

We will review this PR within 3 days.

**Comment by nugmanoff** [comment]
@Sheeri sure thing, I left a comment :)

**Review by Sheeri — APPROVED** [review]
When attempting to run this on the emulator (iphone 11), I'm not getting any keyboard popping up at all, and this error shows up:

2020-09-30 22:41:06.197032-0400 O-FISH[15298:23300526] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitTruffle-NumberPad; using 25901_PortraitTruffle_iPhone-Simple-Pad_Default

I was able to fix it by going to:
I/O -> Keyboard -> Connect Hardware Keyboard (so it is unselected)

and I got it to work, it showed the numeric keypad for EMS Registry number but the regular keypad for the other fields.

**Comment by Sheeri** [comment]
@nugmanoff Congratulations! Upon reviewing your code we have accepted it into the project.

Your code has been merged in!

🎆 🙌 👏 

Thanks so much for submitting great code. We hope you'll pick up another issue soon!

**Comment by Sheeri** [comment]
Hi @nugmanoff! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Pull request merged**
