### PR TITLE
Added CI/CD via Fastlane

### LINKED ISSUE #39: Add CI/CD
As a reviewer and contributor I want to see the code build status (builds or not) on PRs and main branch. 
Platform: Github Actions.

### PR DESCRIPTION
**Pull request by kojiba**
[-] Changed the Gemfile.lock version of Bundler to version of
    Github Actions Mac Machine

Fixes #39

### CODE REVIEW

**Comment by Sheeri** [comment]
It looks like this is something github actions will do, but also something that is done on your machine.

The logic seems to be: when you push code (e.g. git push origin BRANCH_NAME) it will first try to build the code. So if there are build errors, the code won't be pushed. Is that an accurate description?

Can you tell me approximately how long the successful build takes to run locally? (obviously every machine is different, I'm looking for things like 5 seconds, 30 seconds, 5 minutes, 10 minutes, etc.)

**Comment by kojiba** [comment]
I would say that this consists of 2 items:
1. fastlane tool config - this will be do all the iOS-related configuration work i.e. select scheme to build, select simulator, keys if needed, publish if needed and etc
it could be run on local machine, but in our case it will be run only by github actions

2. github actions config - actually a description which to check (master and every update of PR) and it will just call the fastlane to proceed with building/archiving/submitting/signing and etc, so no actual scrips here only github-actions specifics

so to make all the job: github knows about 2, calls 2 when needed, 2 is just calling 1, 1 is knows what to actually do and does all the jobs as orchestrator of lower-level scripts like pure `xcodebuild`

**Comment by Sheeri** [comment]
Thanks for the explanation! Do we have any idea how long it takes approximately to do 1&2, or do we have to merge to find that out? (not sure if you tested it in a forked repo first or something)

**Comment by kojiba** [comment]
On old repot it took approx 6 mins

**Pull request merged**
