### PR TITLE
Update profile photo

### PR DESCRIPTION
**Pull request by Dmitriy-Holovnia**
## Related Issue https://github.com/WildAid/o-fish-ios/issues/400

https://user-images.githubusercontent.com/52383559/163564615-843fc003-79d0-41df-882e-f3ee08bf6404.mp4

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

### CODE REVIEW

**Review by Sheeri — CHANGES_REQUESTED** [review]
Were you able to successfully change the photo when you built the app? When I build it and run it, and click on my profile pic, I am prompted for camera or photo library. I choose one and ....nothing happens. For both. I would expect the camera to show up, or the gallery of photos to show up, depending on which I clicked. Did it work for you?

**Comment by Sheeri** [comment]
If a picture exists, this works great!

**Comment by Sheeri** [comment]
Hi @Dmitriy-Holovnia - can you look into the case when there's no existing picture?

**Comment by Dmitriy-Holovnia** [comment]
> Hi @Dmitriy-Holovnia - can you look into the case when there's no existing picture?
Hi @Sheeri! 
Fixed.

**Review by Sheeri — APPROVED** [review]

**Pull request merged**
