### PR TITLE
Move `realmAppId` to a git-ignorable file

### LINKED ISSUE #329: Move app id to a new, git-ignored file

### PR DESCRIPTION
**Pull request by am-MongoDB**
fixes #329

### CODE REVIEW

**Comment by o-fish-wildaid** [comment]
[Add app-specific details to `.gitignore`](https://trello.com/c/dAASahIV/379-add-app-specific-details-to-gitignore)

**Review by kojiba — APPROVED** [review]
LGTM

**Review by akaktus — APPROVED** [review]
LGTM

**Review by Sheeri — APPROVED** [review]
LGTM

**Pull request merged**
