### PR TITLE
Script to Scan Source and Update Localization Files

### LINKED ISSUE #339: Localization Management system for iOS
We need a localization management system for iOS.

Requirements:
- Open Source

- Ability to show what needs localization and into what languages - either automatically or by running a script

Nice to have:
- Warnings for hard-coded strings that should be internationalized.

- Auto-create issues for localization needs

### PR DESCRIPTION
**Pull request by bladebunny**
## Related Issue

Fixes #339

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [ ] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [x] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 
Added REAME to Scripts directory with instructions and description.

* **Optional: Add any relevant screenshots here**

### CODE REVIEW

**Review by Sheeri — CHANGES_REQUESTED** [review]
@bladebunny this looks great!  (also, thanks for putting in a really great README!)

Just a few nitpicks - in your example in the README,  there's a copy/paste error:
--loc_path=--loc_path=/Projects/o-fish-ios/Localization/

should be:
 --loc_path=--loc_path=/Projects/o-fish-ios/Localization/

Also - can you put the defaults for --verbose and --test? (I think they're both false by default)

For --verbose mode, can you do the following?
- only print out "Adding missing keys to:" if there are actually missing keys added
  - Print "No missing keys to add to FILE" if there are no missing keys
- print out "Adding X missing keys to:" and the count of the missing keys added

Both should be easy using the length of the newKeyset array. (also I wouldn't bother sorting the newKeyset array if it's empty, but that's really a nitpick!)

FWIW I tested and relative paths work, e.g.:
./update_loc.swift --source_path=../ --loc_path=../Localization/ 

This looks so amazing!

**Review by Sheeri — COMMENTED** [review]
One more thing - 
"%@" = "%@";
is coming from this file:
Pods/Realm/Realm/RLMProperty.mm:             "%@"

Would it make sense to ignore anything in the Pods directory?

Also it's putting this in the Localization files:
"R%@ C%@" = "R%@ C%@";

but I can't figure out why it's getting that.
The closest line I can find is:
Pods/Realm/Realm/RLMSyncManager.mm:            util::format("Realm%1/%2", isSwift ? "Swift" : "ObjectiveC",

**Comment by bladebunny** [comment]
You should be able run on it just the project source files.  They'll be in .../o-fish-ios/o-fish-ios.  Two layers in, the outer layer will obviously give you many more hits.  But we could also add a 'skip' list if you find other paths are being included that shouldn't be.

**Comment by bladebunny** [comment]
BTW - yes will make the requested updates later this evening.

**Comment by bladebunny** [comment]
I update based on the review feedback.  Thank you.  I did not add an ignore or blacklist for now.  You should be able to prevent inclusion of Pods directories by just running against o-fish-ios/o-fish-ios (which is at a lower dir level than Pods) ... but I can add ignore lists if its really needed.

**Comment by Sheeri** [comment]
@bladebunny my sincere apologies, I completely missed your update! Will check this right now.

**Comment by Sheeri** [comment]
Hi! I'm still getting "R%@ C%@" = "R%@ C%@"; as a change. But this has waited long enough, and I'm happy with it as-is. I'll add another issue to add a skip list to the script - can we make that be a file in the scripts directory please? that way we can have a list that stays with the code.....(it can be on by default, and people should be able to specify a different file, or no skip list).

e.g.

--skip-list=/path/to/file - by default, "skip_list.txt" in the current directory
--skip-list=false - don't use a skip list.

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Pull request merged**
